### ISSUE TITLE
add flexibility for templateUrl key

### ISSUE THREAD

**Issue by dingzhanjun** [YashdalfTheGray/auto-ngtemplate-loader#19]
**Is your feature request related to a problem?**
currently, the loader looks for "templateUrl:", it does not work if there is space between "templateUrl" and the colon, not sure if this can be enhanced.

**Urgency**
⏰Normal

**Describe the solution you'd like**
use enhanced regex to match "templateUrl :" and "templateUrl:"

By the way, this is a great tool save me a hassle, thanks

**Comment by YashdalfTheGray** [comment]
@dingzhanjun Yeah, I think this is something that can be shipped. Lemme code it up and open a pull request. Would be interested in reviewing it?

**Comment by YashdalfTheGray** [comment]
Check out the pull request that is linked here. Once accepted, I can draft a release in the next day or two.

**Comment by YashdalfTheGray** [comment]
I just published [v2.1.0](https://www.npmjs.com/package/auto-ngtemplate-loader/v/2.1.0)
