### ISSUE TITLE
Work with multiple templateUrl's

### ISSUE THREAD

**Issue by cwramsey** [YashdalfTheGray/auto-ngtemplate-loader#3]
If someone is a bad developer, they'll have multiple directives/components in a single file. This should probably handle that case.

The `reduce` in the `util.js` file could instead start with an empty array and fill it with line numbers.

You could then alter the `if (lineNumber === -1)` to `if (!lineNumbers.length)` for a similar functionality and then loop through those to add the requires as needed.

**Comment by YashdalfTheGray** [comment]
#4 closes this.
